CREATE SCHEMA wht;

CREATE TABLE wht.PROJECTS (
	PROJECT_ID SERIAL PRIMARY KEY,
	PROJECT_NAME VARCHAR(200) NOT NULL,
	MODEL_ID integer NOT NULL,
	START_DATE date,
	END_DATE date,
	START_PHOTO bytea, 
	END_PHOTO bytea,
	NOTES VARCHAR,
	USER_ID integer NOT NULL
);

CREATE TABLE wht.USERS (
	USER_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL
);

CREATE SCHEMA wht_ref;

CREATE TABLE wht_ref.GAME_TYPES (
	GAME_TYPE_ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL
);

CREATE TABLE wht_ref.MODELS (
	MODEL_ID SERIAL PRIMARY KEY,
	MODEL_NAME VARCHAR NOT NULL,
	GAME_TYPE_ID INTEGER NOT NULL,
	UNIT_SIZE INTEGER NOT NULL
);

