CREATE SCHEMA wht;

CREATE TABLE wht.PROJECTS (
	PROJECT_ID SERIAL PRIMARY KEY,
	PROJECT_NAME VARCHAR(200) NOT NULL,
	MODEL_ID integer NOT NULL,
	START_DATE date,
	END_DATE date,
	START_PHOTO bytea, 
	END_PHOTO bytea,
	NOTES VARCHAR,
	USER_ID integer NOT NULL
);