-- SCHEMA BLOCK BEGIN
CREATE SCHEMA IF NOT EXISTS wht;

CREATE SCHEMA IF NOT EXISTS wht_ref;
-- SCHEMA BLOCK END


-- TABLE CREATION BLOCK BEGIN
CREATE TABLE IF NOT EXISTS wht.PROJECTS (
	PROJECT_ID SERIAL PRIMARY KEY,
	PROJECT_NAME VARCHAR(200) NOT NULL,
	MODEL_ID integer NOT NULL,
	START_DATE date,
	END_DATE date,
	START_PHOTO bytea, 
	END_PHOTO bytea,
	NOTES VARCHAR,
	USER_ID integer NOT NULL
);

CREATE TABLE IF NOT EXISTS wht.USERS (
	USER_ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS wht_ref.GAME_TYPES (
	GAME_TYPE_ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS wht_ref.MODELS (
	MODEL_ID SERIAL PRIMARY KEY,
	MODEL_NAME VARCHAR NOT NULL,
	GAME_TYPE_ID INTEGER NOT NULL,
	FACTION VARCHAR NOT NULL,
	UNIT_SIZE_MIN INTEGER NOT NULL,
	UNIT_SIZE_MAX INTEGER NOT NULL
);
-- TABLE CREATION BLOCK END

-- FOREIGN KEY CREATION BLOCK BEGIN
ALTER TABLE wht.PROJECTS 
DROP CONSTRAINT IF EXISTS fk_projects_users;

ALTER TABLE wht.PROJECTS
ADD CONSTRAINT fk_projects_users FOREIGN KEY (USER_ID) REFERENCES wht.USERS (USER_ID);

ALTER TABLE wht.PROJECTS
DROP CONSTRAINT IF EXISTS fk_projects_models;

ALTER TABLE wht.PROJECTS
ADD CONSTRAINT fk_projects_models FOREIGN KEY (MODEL_ID) REFERENCES wht_ref.MODELS (MODEL_ID);

ALTER TABLE wht_ref.MODELS
DROP CONSTRAINT IF EXISTS fk_models_game_types;

ALTER TABLE wht_ref.MODELS
ADD CONSTRAINT fk_models_game_types FOREIGN KEY (GAME_TYPE_ID) REFERENCES wht_ref.GAME_TYPES (GAME_TYPE_ID);
-- FOREIGN KEY CREATION BLOCK END

-- REFERENCE TABLE DATA INSERT BEGIN
TRUNCATE TABLE wht_ref.GAME_TYPES RESTART IDENTITY CASCADE;

INSERT INTO wht_ref.GAME_TYPES 
(NAME)
VALUES 
('Age of Sigmar'),
('Warhammer 40,000'),
('Warcry'),
('Kill Team'),
('Age of Sigmar & Warcry'),
('Warhammer 40,000 & Kill Team');


-- REFERENCE TABLE DATA INSERT END